### ISSUE TITLE
ImportError: No module named amcache.amcache_interface

### ISSUE THREAD

**Issue by jmmalcala** [DFIRKuiper/Kuiper#13]
Hello,

Uploading a Hoarder zip file with  Amcache hive, but if you select to parse  all Amcache on Kuiper, Kuiper not parse any other hives and shows this error on Kuiper-celery.log

`Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 385, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flask_celery.py", line 229, in __call__
    return task_base.__call__(self, *_args, **_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 648, in __protected_call__
    return self.run(*args, **kwargs)
  File "/home/kuiper/Kuiper/app/controllers/parser_management.py", line 296, in run_parserss
    start_parsing_files(main_case_id , machine_case_id , parser_files_mapping[parser]['parser_details'] , parser_files_mapping[parser]['files_to_be_parsed'])
  File "/home/kuiper/Kuiper/app/controllers/parser_management.py", line 215, in start_parsing_files
    parser_module = importlib.import_module('app.parsers.' + parser_folder + '.' + parser_file )
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)`

I think there are two amcache parsers on Kuiper:

![image](https://user-images.githubusercontent.com/11440934/76613216-02e1d400-651e-11ea-9f89-cfdbb11db61c.png)

If you disable amcache in red colour, it works.

Thank you so much.

**Comment by salehmuhaysin** [comment]
Hi jmmalcala

thanks for the notice, "amcache" was the old amcache parser which should be in seperate file "/app/parsers/amcache", the new parser "Amcache" placed as a plugin in "regsk" registry parser "/app/parsers/regsk/"

however we deleted the old one but not deleted from the database -_-
thank you and we will fix this in the next release
