### ISSUE TITLE
TypeError: string indices must be integers, not str

### ISSUE THREAD

**Issue by jmmalcala** [DFIRKuiper/Kuiper#14]
Hello,

Selecting all artifacts to parse on Kuiper, Kuiper doesn´t finish to parse due to the following error on Kuiper-Celery.log:

`ERROR/ForkPoolWorker-3] Task app.controllers.parser_management.run_parserss[98d328a8-a0f7-4225-a00c-03c4a51233ec] raised unexpected: TypeError('string indices must be integers, not str',)
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 385, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flask_celery.py", line 229, in __call__
    return task_base.__call__(self, *_args, **_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 648, in __protected_call__
    return self.run(*args, **kwargs)
  File "/home/kuiper/Kuiper/app/controllers/parser_management.py", line 296, in run_parserss
    start_parsing_files(main_case_id , machine_case_id , parser_files_mapping[parser]['parser_details'] , parser_files_mapping[parser]['files_to_be_parsed'])
  File "/home/kuiper/Kuiper/app/controllers/parser_management.py", line 247, in start_parsing_files
    p = db_es.bulk_queue_push(json_res[ i : (i+chunks_size) ] ,case_id, source = parser_details['name'] , machine = machine_id , data_type=parser_details['name'] , data_path = f)
  File "/home/kuiper/Kuiper/app/database/elkdb.py", line 175, in bulk_queue_push
    push_es = self.bulk_to_elasticsearch( bulk_queue , case_id )
  File "/home/kuiper/Kuiper/app/database/elkdb.py", line 201, in bulk_to_elasticsearch
    status = err["index"]["status"]
TypeError: string indices must be integers, not str`

Thank you for your effort.

**Comment by salehmuhaysin** [comment]
thanks jmmalcala ,

this bug will be solved in next release :)
